# Generated by Django 3.2 on 2020-12-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowModel', '0003_auto_20201211_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
